"use client";

import { useState } from "react";

type QrControlsProps = {
  canonicalUrl: string;
  enabled: boolean;
};

function qrBasePath(canonicalUrl: string) {
  try {
    const path = new URL(canonicalUrl).pathname;
    return /^\/b\/[a-z0-9]+(?:-[a-z0-9]+)*$/.test(path) ? path : null;
  } catch {
    return null;
  }
}

export function QrControls({ canonicalUrl, enabled }: QrControlsProps) {
  const [message, setMessage] = useState("");
  const basePath = qrBasePath(canonicalUrl);
  const available = enabled && basePath !== null;

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(canonicalUrl);
      setMessage("링크를 복사했습니다.");
    } catch {
      setMessage("링크를 복사하지 못했습니다.");
    }
  }

  return (
    <section className="qr-controls" aria-labelledby="qr-controls-title">
      <div className="qr-controls-heading">
        <div>
          <p className="section-kicker">CANONICAL QR</p>
          <h3 id="qr-controls-title">QR 공유</h3>
        </div>
        <p>QR에는 비밀번호나 접근 토큰 없이 고정 주소만 들어갑니다.</p>
      </div>

      {available ? (
        <div className="qr-controls-content">
          <div className="qr-preview-frame">
            {/* Route output is generated by the QR library, never user markup. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              alt="안내판 QR 미리보기"
              height="240"
              src={`${basePath}/qr.svg?preview=1`}
              width="240"
            />
          </div>
          <div className="qr-control-actions">
            <button onClick={() => void copyLink()} type="button">
              링크 복사
            </button>
            <a download href={`${basePath}/qr.png`}>
              PNG 다운로드
            </a>
            <a download href={`${basePath}/qr.svg`}>
              SVG 다운로드
            </a>
            {message ? <p role="status">{message}</p> : null}
          </div>
        </div>
      ) : (
        <p className="qr-unavailable">게시한 뒤 QR을 사용할 수 있습니다.</p>
      )}
    </section>
  );
}
